name: Tests

on:
  push:
    branches:
      - main
      - local
  pull_request:

jobs:
  test:
    runs-on: ubuntu-latest
    services:
      mysql: 
        image: mysql:8
        env:
          MYSQL_ALLOW_EMPTY_PASSWORD: yes
          MYSQL_DATABASE: inventory_system
        ports:
          - 3306:3306
        options: --health-cmd="mysqladmin ping" --health-interval=10s --health-timeouts=5s --health-retries=3

    strategy:
      fail-fast: true

    name: MySQL 8

    steps:
    - name: Checkout Code
      uses: actions/checkout@v3
    
    - name: Setup PHP
      uses: shivammathur/setup-php@v2
      with:
        php-version: '8.1'
    
    - name: Copy .env
      run: php -r "file_exists('.env') || copy('.env.example, .env');"
    
    - name: Install Dependencies
      run: |
        composer update --no-scripts --prefer-stable --prefer-dist --no-interaction --no-progress
        npm install
    
    - name: Generate Application Key
      run: php artisan key:generate

    - name: Run Tests
      run: php artisan test
      env:
        DB_CONNECTION: mysql
        DB_USERNAME: root